version: '3.7'
services:

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always